export const INGREDIENTS = ['🐤', '🐮', '🌮', '🥬', '🐟', '🐷', '🥚'];

export const MEALS = [
	{ name: 'Pollo en salsa verde', season: 'ANY', ingredients: [INGREDIENTS[0]] },
	{ name: 'Pollo en mole', season: 'ANY', ingredients: [INGREDIENTS[0]] },
	{ name: 'Pollo en pipian', season: 'ANY', ingredients: [INGREDIENTS[0]] },
	{ name: 'Pollo rostizado', season: 'ANY', ingredients: [INGREDIENTS[0]] },
	{ name: 'Muslos empanizados', season: 'ANY', ingredients: [INGREDIENTS[0]] },
	{ name: 'Caldo de pollo', season: 'COLD', ingredients: [INGREDIENTS[0], INGREDIENTS[3]] },
	{ name: 'Mole de epazote', season: 'COLD', ingredients: [INGREDIENTS[0]] },
	{ name: 'Enchiladas verdes', season: 'ANY', ingredients: [INGREDIENTS[2], INGREDIENTS[0]] },
	{ name: 'Enmoladas', season: 'ANY', ingredients: [INGREDIENTS[2], INGREDIENTS[0]] },
	{ name: 'Tacos dorados de pollo', season: 'ANY', ingredients: [INGREDIENTS[2], INGREDIENTS[0]] },
	{ name: 'Sopes', season: 'ANY', ingredients: [INGREDIENTS[2]] },
	{ name: 'Quesadillas de papa', season: 'ANY', ingredients: [INGREDIENTS[2], INGREDIENTS[3]] },
	{ name: 'Tortas de papa', season: 'HOT', ingredients: [INGREDIENTS[3]] },
	{ name: 'Calabazas picadas', season: 'ANY', ingredients: [INGREDIENTS[3]] },
	{ name: 'Chilaquiles con huevo', season: 'ANY', ingredients: [INGREDIENTS[2], INGREDIENTS[6]] },
	{ name: 'Chilaquiles con carne', season: 'ANY', ingredients: [INGREDIENTS[2], INGREDIENTS[1]] },
	{ name: 'Verdolagas', season: 'ANY', ingredients: [INGREDIENTS[3], INGREDIENTS[1]] },
	{ name: 'Pozole de pollo', season: 'COLD', ingredients: [INGREDIENTS[0]] },
	{ name: 'Pozole de puerco', season: 'COLD', ingredients: [INGREDIENTS[5]] },
	{ name: 'Mole de olla', season: 'COLD', ingredients: [INGREDIENTS[1], INGREDIENTS[3]] },
	{ name: 'Picadillo', season: 'ANY', ingredients: [INGREDIENTS[1], INGREDIENTS[3]] },
	{ name: 'Albóndigas', season: 'ANY', ingredients: [INGREDIENTS[1]] },
	{ name: 'Bistec encebollado', season: 'ANY', ingredients: [INGREDIENTS[1]] },
	{ name: 'Bistec en salsa verde', season: 'ANY', ingredients: [INGREDIENTS[1]] },
	{ name: 'Bistec a la mexicana', season: 'ANY', ingredients: [INGREDIENTS[1], INGREDIENTS[3]] },
	{ name: 'Carne en coca-cola', season: 'ANY', ingredients: [INGREDIENTS[5]] },
	{ name: 'Chipotle quemado', season: 'ANY', ingredients: [INGREDIENTS[5]] },
	{ name: 'Chuleta con nopales', season: 'ANY', ingredients: [INGREDIENTS[5], INGREDIENTS[3]] },
	{ name: 'Atún con verdura', season: 'HOT', ingredients: [INGREDIENTS[4], INGREDIENTS[3]] },
	{ name: 'Tortas de sardina', season: 'HOT', ingredients: [INGREDIENTS[4]] },
	{ name: 'Filete empanizado', season: 'HOT', ingredients: [INGREDIENTS[4]] },
];
